finchcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    path('finches/<int:finch_id>/', views.finches_detail, name='detail'),
    path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
    path('finches/<int:pk>/update/',
         views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/',
         views.FinchDelete.as_view(), name='finches_delete')
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

MEALS = (
    ('V', 'Vegetarian'),
    ('C', 'Carnivore'),
    ('O', 'Omnivore')
)


class Finch(models.Model):
    name = models.CharField(max_length=100)
    beak = models.CharField(max_length=100)
    description = models.TextField()
    age = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})


class Feeding(models.Model):
    date = models.DateField('feeding date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )

    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_meal_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding


class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Finch, Feeding
from .forms import FeedingForm

# Create your views here.


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', {
        'finches': finches
    })


def finches_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    # instantitate feeding form to be rendered in the template
    feeding_form = FeedingForm()
    return render(request, 'finches/detail.html', {
        # include the finch and feeding form in the context
        'finch': finch,
        'feeding_form': feeding_form
    })


class FinchCreate(CreateView):
    model = Finch
    fields = '__all__'


class FinchUpdate(UpdateView):
    model = Finch
    fields = ['beak', 'description', 'age']


class FinchDelete(DeleteView):
    model = Finch
    success_url = "/finches/"

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>About the Finch Collector</h1>
<hr />
<p>Hire the Finch Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
</head>

<body>
  <header class="navbar-fixed">
    <nav class="blue">
      <div class="nav-wrapper">
        <ul>
          <li>
            <a href="/" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a>
          </li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
          <li><a href="{% url 'index' %}">View All My Finches</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %} {% endblock %}
  </main>
  <footer class="page-footer, blue">
    <div class="right">
      All Rights Reserved, &copy; 2020 Finch Collector &nbsp;
    </div>
  </footer>
</body>

</html>

main_app/templates/finches/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Finch Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ finch.name }}</span>
    <p>Beak: {{ finch.beak }}</p>
    <p>Description: {{ finch.description }}</p>
    {% if finch.age > 0 %}
    <p>Age: {{ finch.age }}</p>
    {% else %}
    <p>Age: Little birdie</p>
    {% endif %}
  </div>
  <div class="card-action">
    <a class="red-text" href="{% url 'finches_update' finch.id %}">Edit</a>
    <a class="red-text" href="{% url 'finches_delete' finch.id %}">Delete</a>
  </div>
</div>
<div class="col s6">
  <table class="striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Meal</th>
      </tr>
    </thead>
    <tbody>
      {% for feeding in finch.feeding_set.all %}
      <tr>
        <td>{{feeding.date}}</td>
        <td>{{feeding.get_meal_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %} {% block content %}

<h1>My Finches</h1>

{% for finch in finches %}
<a href="{% url 'detail' finch.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ finch.name }}</span>
      <p>Beak: {{ finch.beak }}</p>
      <p>Description: {{ finch.description }}</p>
      {% if finch.age > 0 %}
      <p>Age: {{ finch.age }}</p>
      {% else %}
      <p>Age: Little birdie</p>
      {% endif %}
    </div>
  </div>
</a>

{% endfor%} {%endblock%}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Home</h1>
<p>
  Here you can gaze at the wide range of finches that have been collected in the
  Galapagos by world-renowned scientist, Charles Darwin (and Jorge Galvan).
</p>

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Finch</h1>
<h4>
  Are you sure you want to delete
  <span class="teal-text">{{ object.name }}</span>?
</h4>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn" />
  <a href="{% url 'detail' finch.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %} {% block content %} {% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Finch</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}